stages:
  - stage: Check
    jobs:
      - job: Check
        displayName: Sanity Check
        pool:
          vmImage: 'ubuntu-16.04'
        container: 'rust:latest'
        steps:
          - script: rustup component add clippy rustfmt
            displayName: Install clippy and rustfmt
          - script: cargo fmt -- --check
            displayName: Check Formatting
          - script: cargo check --all
            displayName: Check
          - script: cargo clippy
            displayName: Clippy

  - stage: Build
    jobs:
      - job: BuildDocker
        displayName: Build Docker Image
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            displayName: Login to Dockerhub
            inputs:
              command: login
              containerRegistry: Dockerhub
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: darwish/alma
              tags: |
                latest
