stages:
  - stage: Check
    jobs:
      - job: Check
        displayName: Sanity Check
        pool:
          vmImage: 'ubuntu-16.04'
          container: 'rust:latest'
        steps:
          - script: cargo check --all
            displayName: Run check

  - stage: Build
    jobs:
      - job: BuildDocker
        displayName: Build Docker Image
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            displayName: Login to Dockerhub
            inputs:
              command: login
              containerRegistry: Dockerhub
          - task: Docker@2
            displayName: Build and Push
            inputs:
              command: buildAndPush
              repository: darwish/alma
              tags: |
                latest
