[package]
name = "alma"
version = "0.4.0"
authors = ["Roey Darwish Dror"]
edition = "2018"

[dependencies]
which = "2.0.1"
failure = "0.1.3"
log = "0.4.6"
structopt = "0.2.13"
simplelog = "0.5.3"
tempfile = "3.0.5"
nix = "0.12.0"
