[package]
name = "alma"
version = "0.9.0"
authors = ["Roey Darwish Dror"]
edition = "2018"

[dependencies]
which = "2.0.1"
failure = "0.1.5"
log = "0.4.6"
structopt = "0.2.14"
tempfile = "3.0.5"
serde = { version = "1.0.92", features = ["derive"] }
toml = "0.5.1"
byte-unit = "3.0.1"
nix = "0.14.1"
env_logger = "0.6.2"
pretty_env_logger = "0.3.0"
dialoguer = "0.4.0"
