[package]
name = "alma"
version = "0.7.0"
authors = ["Roey Darwish Dror"]
edition = "2018"

[dependencies]
which = "2.0.1"
failure = "0.1.5"
log = "0.4.6"
structopt = "0.2.14"
simplelog = "0.5.3"
tempfile = "3.0.5"
serde = { version = "1.0.92", features = ["derive"] }
toml = "0.5.1"
byte-unit = "2.1.0"
ctrlc = "3.1.3"
nix = "0.14.1"
